<?php return array (
  'DISTRICT_ID' => '1',
  'DISTRICT_NAME' => 'UK',
  'FACILITY_LEVEL_ID' => '2',
  'FACILITY_ID' => '123',
  'FACILITY_NAME' => 'New York',
  'FACILITY_CODE' => 'CPHL01',
  'FACILITY_OWNERSHIP_ID' => '1',
  'FIN_YEAR_ID' => '1',
  'FIN_YEAR_NAME' => '2022/2023',
  'INCOMING_STOCK_FLAG' => 'I',
  'OUTGOING_STOCK_FLAG' => 'O',
  'LOSSES_ADJUSTMENTS_STOCK_FLAG' => 'A',
  'FROM_FACILITY' => '1',
  'FROM_WAREHOUSE' => '2',
  'TO_FACILITY' => '3',
  'TO_PERSON' => '4',
  'EID_CONNECT' => 'https://www.cphluganda.org/poc_data_pull/',
  'HPV_CONNECT' => 'https://www.cphluganda.org/alis_api/',
  'VL_CONNECT' => 'https://vldash.cphluganda.org/poc_viral_load_data/',
);